name: "mlpf"
platform: "tensorflow_graphdef"
max_batch_size: 0 
input [
  {
    name: "x"
    data_type: TYPE_FP32
    dims: [ -1, 15 ]
  }
]
output [
  {
    name: "Identity"
    data_type: TYPE_FP32
    dims: [ -1, 12 ]
  }
]
